name: Tests

on: push

jobs:
  lint:
    name: Test code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install
      - name: Start containers
        run: ./vendor/bin/sail up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Check running containers
        run: docker ps
      - name: Run tests
        run: make test
